# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-19 01:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gamificacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nivel',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='puntuacion',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='recompensa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gamificacion.Recompensa'),
        ),
    ]
