# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-19 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.CharField(max_length=144)),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=500)),
                ('presupuesto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gasto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fondos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('like', models.IntegerField()),
                ('dislike', models.IntegerField()),
            ],
        ),
    ]
